#!/bin/sh
IFNAME="$1"
BRNAME="ngbr0"

# Find next link number:
LNUM=2
while ngctl msg $BRNAME: getstats $LNUM \
        > /dev/null 2>&1
do
        LNUM=$(( $LNUM + 1 ))
done

ngctl mkpeer $BRNAME: eiface link$LNUM ether
NGIF=$( set -- `ngctl show -n "$BRNAME:link$LNUM"` && echo $2 )
ngctl name $NGIF: $IFNAME
ifconfig $NGIF name $IFNAME
