# /etc/jail.conf.d/jail_skel.conf
#
# Simple VNET jail using Netgraph Buddy. Matching the jail name with the
# interface name and path keeps configuration straightforward. This jail uses
# the companion devfs.rules example to allow DHCP, pf, and System V IPC
# primitives (for applications like PostgreSQL).
#
# When using this as a template, change $bridge and the jail name as desired.

$bridge = "public";
jail_skel {
	$if_name = "$name";
	path = "/jail/$name";
	vnet;
	vnet.interface = "$if_name";
	host.hostname = "$name";
	exec.clean;
	exec.prestart = "service ngbuddy jail $if_name $bridge";
	exec.start = "/bin/sh /etc/rc";
	exec.prestop = "service ngbuddy unjail $if_name $name";
	exec.stop = "/bin/sh /etc/rc.shutdown";
	devfs_ruleset = 25;
	mount.devfs;
	allow.set_hostname = 1;
	allow.raw_sockets;
	sysvsem = new;
	sysvshm = new;
	sysvmsg = new;
}
